name: CI/CD Pipeline for resolve-frontend-parceiro PROD update v3.1

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: "resourceresolve.azurecr.io/resolve-frontend-parceiro"
  AKS_CLUSTER_NAME: "Resolve-AKS-Web"
  AKS_RESOURCE_GROUP: "Resolve"
  NAMESPACE: "resolve-parceiro"
  DEPLOYMENT_NAME: "resolve-frontend-parceiro"

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    environment: Resolve-env

    steps:
      # 1. Checkout do Código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Log in ao Azure Container Registry
      - name: Log in to Azure Container Registry
        run: echo "${{ vars.AZURE_ACR_PASSWORD }}" | docker login resourceresolve.azurecr.io -u "${{ vars.AZURE_ACR_USERNAME }}" --password-stdin

      # 3. Criar o arquivo .env com as variáveis do GitHub Secrets
      - name: Create .env File
        run: |
          echo "NEXT_PUBLIC_ONESIGNAL_APP_ID=${{ vars.NEXT_PUBLIC_ONESIGNAL_APP_ID}}" >> .env
          echo "NEXT_PUBLIC_ONESIGNAL_REST_API_KEY=${{ vars.NEXT_PUBLIC_ONESIGNAL_REST_API_KEY}}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY}}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}" >> .env
          
      # 4. Build e Push da Imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build --no-cache --build-arg ENV_FILE=.env -t "${DOCKER_IMAGE}:${{ github.sha }}" .
          docker push "${DOCKER_IMAGE}:${{ github.sha }}"

      # 5. Log in ao Azure CLI
      - name: Log in to Azure CLI
        run: az login --service-principal -u "${{ vars.AZURE_CLIENT_ID }}" -p "${{ vars.AZURE_CLIENT_SECRET }}" --tenant "${{ vars.AZURE_TENANT_ID }}"

      # 6. Configurar Acesso ao Cluster AKS
      - name: Configure Access to AKS
        run: az aks get-credentials --resource-group "$AKS_RESOURCE_GROUP" --name "$AKS_CLUSTER_NAME" --overwrite-existing

      
      # 7. Atualizar a Imagem do Deployment no AKS
      - name: Update Deployment on AKS
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME resolve-frontend-parceiro="${DOCKER_IMAGE}:${{ github.sha }}" -n "$NAMESPACE"
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n "$NAMESPACE"

      